connector:
    twitter:
        consumer-key        : RPkKrwvvG6KszMTG4ISkETygH
        consumer-secret     : P7dKtHUExfP57Kdj7usCB3zMuYwiHxMuCQWEVjkBdl9KmHT5KH
        access-token        : 3142269147-KmeWih2olwDo38c5vZq8u8lYs7PfcYk2Kh5v1gj
        access-token-secret : 71yFEdwBlFC3vsgjMGBwh5hzHtRW166i5G6dctss4SHf5
    google-sheets:
        application-name    : MySpreadsheetIntegration
        client-id           : 271685667525-0o2jhghl7fts88vojtjg0n5ql3hd6ueo.apps.googleusercontent.com
        client-secret       : bEof69SyqLx56a5Kx1oko_PB
        access-token        : ya29.dAJBb45YNoRCbp0-OLFxf-pOcKYIbgu5_06OhTqgRIcglclQacuFaY-ThVeT5F8ZVrYXdqE
        refresh-token       : 1/B1PbI8PloZ4_UtrJPIvtJaZb0Jddx4GHPLxqPggEaWJIgOrJDtdun6zK6XiATCKT
        