connector:
    twitter:
        consumer-key        : Your Consumer Key Here
        consumer-secret     : Your Consumer Secret Here
        access-token        : Your Access Token Here
        access-token-secret : Your Access Token Secret Here
    google-sheets:
        application-name    : Your App Name Here
        client-id           : Your Client Id Here
        client-secret       : Your Client Secret Here
        access-token        : Your Access Token Here
        refresh-token       : Your Refresh Token Here
        