connector:
    twitter:
        consumer-key        : Consumer Key
        consumer-secret     : Consumer Secret
        access-token        : Access Token
        access-token-secret : Access Token Secret
    google-sheets:
        application-name    : Application Name
        client-id           : Client ID
        client-secret       : Client Secret
        access-token        : Access Token
        refresh-token       : Refresh Token
        